import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AnimationExtractor {
    private static final Map<String, String> REGION_MODIFIER_MAP = new HashMap<>();
    private static final Map<String, String> TYPE_MODIFIER_MAP = new HashMap<>();
    private static final Map<String, String> SPECIES_MAP = new HashMap<>();
    private static final List<String> ERRORS = new ArrayList<>();
    private static final Path TARGET_PATH = Paths.get("F:\\NewAttempt\\ScarletViolet\\animationRepoTesting");

    public static void main(String[] args) throws IOException {
        var dataPath = Paths.get("F:\\NewAttempt\\ScarletViolet\\pokemon\\data");
        Files.createDirectories(TARGET_PATH);

        var svPokemon = Files.list(dataPath).toList();
        for (var pkmn : svPokemon) {
            var fileName = pkmn.getFileName().toString();
            if (fileName.length() != "pm####".length()) System.err.println("Invalid folder \"" + fileName + "\"");
            else {
                var species = SPECIES_MAP.getOrDefault(fileName.substring(2), fileName);
                var forms = Files.list(pkmn).toList();
                for (var form : forms) {
                    var formName = form.getFileName().toString();
                    if (formName.length() != "pm####_##_##".length())
                        System.err.println("Invalid form name \"" + fileName + "\"");
                    var importantNumbers = formName.substring("pm####_".length()).split("_");
                    var region = REGION_MODIFIER_MAP.computeIfAbsent(importantNumbers[1], AnimationExtractor::fillInMissingRegion);
                    var type = TYPE_MODIFIER_MAP.computeIfAbsent(importantNumbers[0], AnimationExtractor::fillInMissingType);
                    var subPath = "";
                    if (region != null) subPath += "_" + region;
                    if (type != null) subPath += "_" + type;
                    if (subPath.equals("")) subPath = "default";

                    var pkmnOutPath = TARGET_PATH.resolve(species).resolve(subPath);
                    Files.createDirectories(pkmnOutPath);
                    Files.walk(pkmnOutPath)
                            .filter(Files::isRegularFile)
                            .forEach(path -> {
                                try {
                                    Files.delete(path);
                                } catch (IOException e) {
                                    throw new RuntimeException(e);
                                }
                            });
                    Files.list(form)
                            .filter(AnimationExtractor::isAnimationFile)
                            .filter(AnimationExtractor::validateAnimation)
                            .forEach(path -> {
                                try {
                                    Files.copy(path, AnimationExtractor.getReadableAnimationName(pkmnOutPath, fixAnimationFileType(path)));
                                } catch (IOException e) {
                                    throw new RuntimeException("Failed to copy animation", e);
                                }
                            });
                }
            }
        }

        Files.writeString(TARGET_PATH.resolve("results.txt"), String.join("\n", ERRORS));
    }

    private static boolean validateAnimation(Path path) {
        // check for animations in the wrong folder
        var parentFileName = path.getParent().getFileName().toString();
        var animFileName = path.getFileName().toString().substring(0, parentFileName.length());
        return parentFileName.equals(animFileName);
    }

    private static Path getReadableAnimationName(Path pkmnOutPath, Path path) {
        var fileName = path.getFileName().toString().substring("pm####_##_##_".length());
        int transport = Integer.parseInt(fileName.substring(0, 1));
        fileName = fileName.substring("#####_".length());
        if (transport == 1)
            fileName = "swim_" + fileName;
        else if (transport == 2)
            fileName = "fly_" + fileName;
        var result = pkmnOutPath.resolve(fileName);
        if (Files.exists(result)) {
            System.err.println("Duplicate animation! " + result);
            ERRORS.add("Duplicate animation! " + result);
            result = pkmnOutPath.resolve(path.getFileName());
        }

        return result;
    }

    private static Path fixAnimationFileType(Path path) {
        if (path.getFileName().toString().endsWith("gfbanm")) {
            return path.getParent().resolve(path.getFileName().toString().replace(".gfbanm", ".tranm"));
        } else return path;
    }

    private static boolean isAnimationFile(Path path) {
        return path.toString().endsWith(".gfbanm");
    }

    private static String fillInMissingType(String s) {
        if (s.equals("00")) return null;
        return "type" + s;
    }

    private static String fillInMissingRegion(String s) {
        if (s.equals("00")) return null;
        return "region" + s;
    }

    static {
        REGION_MODIFIER_MAP.put("11", "alolan");
        REGION_MODIFIER_MAP.put("61", "alolan");
        REGION_MODIFIER_MAP.put("31", "galarian");
        REGION_MODIFIER_MAP.put("41", "hisuian");
        REGION_MODIFIER_MAP.put("51", "paldean");

        TYPE_MODIFIER_MAP.put("01", "female");
        TYPE_MODIFIER_MAP.put("12", "battle");
        TYPE_MODIFIER_MAP.put("51", "mega1");
        TYPE_MODIFIER_MAP.put("52", "mega2");
        TYPE_MODIFIER_MAP.put("81", "gigantamax");
        TYPE_MODIFIER_MAP.put("71", "noble");

        SPECIES_MAP.put("9999", "SUB_DOLL");
        SPECIES_MAP.put("0000", "MISSING");
        SPECIES_MAP.put("0001", "Bulbasaur");
        SPECIES_MAP.put("0002", "Ivysaur");
        SPECIES_MAP.put("0003", "Venusaur");
        SPECIES_MAP.put("0004", "Charmander");
        SPECIES_MAP.put("0005", "Charmeleon");
        SPECIES_MAP.put("0006", "Charizard");
        SPECIES_MAP.put("0007", "Squirtle");
        SPECIES_MAP.put("0008", "Wartortle");
        SPECIES_MAP.put("0009", "Blastoise");
        SPECIES_MAP.put("0010", "Caterpie");
        SPECIES_MAP.put("0011", "Metapod");
        SPECIES_MAP.put("0012", "Butterfree");
        SPECIES_MAP.put("0013", "Weedle");
        SPECIES_MAP.put("0014", "Kakuna");
        SPECIES_MAP.put("0015", "Beedrill");
        SPECIES_MAP.put("0016", "Pidgey");
        SPECIES_MAP.put("0017", "Pidgeotto");
        SPECIES_MAP.put("0018", "Pidgeot");
        SPECIES_MAP.put("0019", "Rattata");
        SPECIES_MAP.put("0020", "Raticate");
        SPECIES_MAP.put("0021", "Spearow");
        SPECIES_MAP.put("0022", "Fearow");
        SPECIES_MAP.put("0023", "Ekans");
        SPECIES_MAP.put("0024", "Arbok");
        SPECIES_MAP.put("0025", "Pikachu");
        SPECIES_MAP.put("0026", "Raichu");
        SPECIES_MAP.put("0027", "Sandshrew");
        SPECIES_MAP.put("0028", "Sandslash");
        SPECIES_MAP.put("0029", "Nidoran♀");
        SPECIES_MAP.put("0030", "Nidorina");
        SPECIES_MAP.put("0031", "Nidoqueen");
        SPECIES_MAP.put("0032", "Nidoran♂");
        SPECIES_MAP.put("0033", "Nidorino");
        SPECIES_MAP.put("0034", "Nidoking");
        SPECIES_MAP.put("0035", "Clefairy");
        SPECIES_MAP.put("0036", "Clefable");
        SPECIES_MAP.put("0037", "Vulpix");
        SPECIES_MAP.put("0038", "Ninetales");
        SPECIES_MAP.put("0039", "Jigglypuff");
        SPECIES_MAP.put("0040", "Wigglytuff");
        SPECIES_MAP.put("0041", "Zubat");
        SPECIES_MAP.put("0042", "Golbat");
        SPECIES_MAP.put("0043", "Oddish");
        SPECIES_MAP.put("0044", "Gloom");
        SPECIES_MAP.put("0045", "Vileplume");
        SPECIES_MAP.put("0046", "Paras");
        SPECIES_MAP.put("0047", "Parasect");
        SPECIES_MAP.put("0048", "Venonat");
        SPECIES_MAP.put("0049", "Venomoth");
        SPECIES_MAP.put("0050", "Diglett");
        SPECIES_MAP.put("0051", "Dugtrio");
        SPECIES_MAP.put("0052", "Meowth");
        SPECIES_MAP.put("0053", "Persian");
        SPECIES_MAP.put("0054", "Psyduck");
        SPECIES_MAP.put("0055", "Golduck");
        SPECIES_MAP.put("0056", "Mankey");
        SPECIES_MAP.put("0057", "Primeape");
        SPECIES_MAP.put("0058", "Growlithe");
        SPECIES_MAP.put("0059", "Arcanine");
        SPECIES_MAP.put("0060", "Poliwag");
        SPECIES_MAP.put("0061", "Poliwhirl");
        SPECIES_MAP.put("0062", "Poliwrath");
        SPECIES_MAP.put("0063", "Abra");
        SPECIES_MAP.put("0064", "Kadabra");
        SPECIES_MAP.put("0065", "Alakazam");
        SPECIES_MAP.put("0066", "Machop");
        SPECIES_MAP.put("0067", "Machoke");
        SPECIES_MAP.put("0068", "Machamp");
        SPECIES_MAP.put("0069", "Bellsprout");
        SPECIES_MAP.put("0070", "Weepinbell");
        SPECIES_MAP.put("0071", "Victreebel");
        SPECIES_MAP.put("0072", "Tentacool");
        SPECIES_MAP.put("0073", "Tentacruel");
        SPECIES_MAP.put("0074", "Geodude");
        SPECIES_MAP.put("0075", "Graveler");
        SPECIES_MAP.put("0076", "Golem");
        SPECIES_MAP.put("0077", "Ponyta");
        SPECIES_MAP.put("0078", "Rapidash");
        SPECIES_MAP.put("0079", "Slowpoke");
        SPECIES_MAP.put("0080", "Slowbro");
        SPECIES_MAP.put("0081", "Magnemite");
        SPECIES_MAP.put("0082", "Magneton");
        SPECIES_MAP.put("0083", "Farfetch’d");
        SPECIES_MAP.put("0084", "Doduo");
        SPECIES_MAP.put("0085", "Dodrio");
        SPECIES_MAP.put("0086", "Seel");
        SPECIES_MAP.put("0087", "Dewgong");
        SPECIES_MAP.put("0088", "Grimer");
        SPECIES_MAP.put("0089", "Muk");
        SPECIES_MAP.put("0090", "Shellder");
        SPECIES_MAP.put("0091", "Cloyster");
        SPECIES_MAP.put("0092", "Gastly");
        SPECIES_MAP.put("0093", "Haunter");
        SPECIES_MAP.put("0094", "Gengar");
        SPECIES_MAP.put("0095", "Onix");
        SPECIES_MAP.put("0096", "Drowzee");
        SPECIES_MAP.put("0097", "Hypno");
        SPECIES_MAP.put("0098", "Krabby");
        SPECIES_MAP.put("0099", "Kingler");
        SPECIES_MAP.put("0100", "Voltorb");
        SPECIES_MAP.put("0101", "Electrode");
        SPECIES_MAP.put("0102", "Exeggcute");
        SPECIES_MAP.put("0103", "Exeggutor");
        SPECIES_MAP.put("0104", "Cubone");
        SPECIES_MAP.put("0105", "Marowak");
        SPECIES_MAP.put("0106", "Hitmonlee");
        SPECIES_MAP.put("0107", "Hitmonchan");
        SPECIES_MAP.put("0108", "Lickitung");
        SPECIES_MAP.put("0109", "Koffing");
        SPECIES_MAP.put("0110", "Weezing");
        SPECIES_MAP.put("0111", "Rhyhorn");
        SPECIES_MAP.put("0112", "Rhydon");
        SPECIES_MAP.put("0113", "Chansey");
        SPECIES_MAP.put("0114", "Tangela");
        SPECIES_MAP.put("0115", "Kangaskhan");
        SPECIES_MAP.put("0116", "Horsea");
        SPECIES_MAP.put("0117", "Seadra");
        SPECIES_MAP.put("0118", "Goldeen");
        SPECIES_MAP.put("0119", "Seaking");
        SPECIES_MAP.put("0120", "Staryu");
        SPECIES_MAP.put("0121", "Starmie");
        SPECIES_MAP.put("0122", "Mr. Mime");
        SPECIES_MAP.put("0123", "Scyther");
        SPECIES_MAP.put("0124", "Jynx");
        SPECIES_MAP.put("0125", "Electabuzz");
        SPECIES_MAP.put("0126", "Magmar");
        SPECIES_MAP.put("0127", "Pinsir");
        SPECIES_MAP.put("0128", "Tauros");
        SPECIES_MAP.put("0129", "Magikarp");
        SPECIES_MAP.put("0130", "Gyarados");
        SPECIES_MAP.put("0131", "Lapras");
        SPECIES_MAP.put("0132", "Ditto");
        SPECIES_MAP.put("0133", "Eevee");
        SPECIES_MAP.put("0134", "Vaporeon");
        SPECIES_MAP.put("0135", "Jolteon");
        SPECIES_MAP.put("0136", "Flareon");
        SPECIES_MAP.put("0137", "Porygon");
        SPECIES_MAP.put("0138", "Omanyte");
        SPECIES_MAP.put("0139", "Omastar");
        SPECIES_MAP.put("0140", "Kabuto");
        SPECIES_MAP.put("0141", "Kabutops");
        SPECIES_MAP.put("0142", "Aerodactyl");
        SPECIES_MAP.put("0143", "Snorlax");
        SPECIES_MAP.put("0144", "Articuno");
        SPECIES_MAP.put("0145", "Zapdos");
        SPECIES_MAP.put("0146", "Moltres");
        SPECIES_MAP.put("0147", "Dratini");
        SPECIES_MAP.put("0148", "Dragonair");
        SPECIES_MAP.put("0149", "Dragonite");
        SPECIES_MAP.put("0150", "Mewtwo");
        SPECIES_MAP.put("0151", "Mew");
        SPECIES_MAP.put("0152", "Chikorita");
        SPECIES_MAP.put("0153", "Bayleef");
        SPECIES_MAP.put("0154", "Meganium");
        SPECIES_MAP.put("0155", "Cyndaquil");
        SPECIES_MAP.put("0156", "Quilava");
        SPECIES_MAP.put("0157", "Typhlosion");
        SPECIES_MAP.put("0158", "Totodile");
        SPECIES_MAP.put("0159", "Croconaw");
        SPECIES_MAP.put("0160", "Feraligatr");
        SPECIES_MAP.put("0161", "Sentret");
        SPECIES_MAP.put("0162", "Furret");
        SPECIES_MAP.put("0163", "Hoothoot");
        SPECIES_MAP.put("0164", "Noctowl");
        SPECIES_MAP.put("0165", "Ledyba");
        SPECIES_MAP.put("0166", "Ledian");
        SPECIES_MAP.put("0167", "Spinarak");
        SPECIES_MAP.put("0168", "Ariados");
        SPECIES_MAP.put("0169", "Crobat");
        SPECIES_MAP.put("0170", "Chinchou");
        SPECIES_MAP.put("0171", "Lanturn");
        SPECIES_MAP.put("0172", "Pichu");
        SPECIES_MAP.put("0173", "Cleffa");
        SPECIES_MAP.put("0174", "Igglybuff");
        SPECIES_MAP.put("0175", "Togepi");
        SPECIES_MAP.put("0176", "Togetic");
        SPECIES_MAP.put("0177", "Natu");
        SPECIES_MAP.put("0178", "Xatu");
        SPECIES_MAP.put("0179", "Mareep");
        SPECIES_MAP.put("0180", "Flaaffy");
        SPECIES_MAP.put("0181", "Ampharos");
        SPECIES_MAP.put("0182", "Bellossom");
        SPECIES_MAP.put("0183", "Marill");
        SPECIES_MAP.put("0184", "Azumarill");
        SPECIES_MAP.put("0185", "Sudowoodo");
        SPECIES_MAP.put("0186", "Politoed");
        SPECIES_MAP.put("0187", "Hoppip");
        SPECIES_MAP.put("0188", "Skiploom");
        SPECIES_MAP.put("0189", "Jumpluff");
        SPECIES_MAP.put("0190", "Aipom");
        SPECIES_MAP.put("0191", "Sunkern");
        SPECIES_MAP.put("0192", "Sunflora");
        SPECIES_MAP.put("0193", "Yanma");
        SPECIES_MAP.put("0194", "Wooper");
        SPECIES_MAP.put("0195", "Quagsire");
        SPECIES_MAP.put("0196", "Espeon");
        SPECIES_MAP.put("0197", "Umbreon");
        SPECIES_MAP.put("0198", "Murkrow");
        SPECIES_MAP.put("0199", "Slowking");
        SPECIES_MAP.put("0200", "Misdreavus");
        SPECIES_MAP.put("0201", "Unown");
        SPECIES_MAP.put("0202", "Wobbuffet");
        SPECIES_MAP.put("0203", "Girafarig");
        SPECIES_MAP.put("0204", "Pineco");
        SPECIES_MAP.put("0205", "Forretress");
        SPECIES_MAP.put("0206", "Dunsparce");
        SPECIES_MAP.put("0207", "Gligar");
        SPECIES_MAP.put("0208", "Steelix");
        SPECIES_MAP.put("0209", "Snubbull");
        SPECIES_MAP.put("0210", "Granbull");
        SPECIES_MAP.put("0211", "Qwilfish");
        SPECIES_MAP.put("0212", "Scizor");
        SPECIES_MAP.put("0213", "Shuckle");
        SPECIES_MAP.put("0214", "Heracross");
        SPECIES_MAP.put("0215", "Sneasel");
        SPECIES_MAP.put("0216", "Teddiursa");
        SPECIES_MAP.put("0217", "Ursaring");
        SPECIES_MAP.put("0218", "Slugma");
        SPECIES_MAP.put("0219", "Magcargo");
        SPECIES_MAP.put("0220", "Swinub");
        SPECIES_MAP.put("0221", "Piloswine");
        SPECIES_MAP.put("0222", "Corsola");
        SPECIES_MAP.put("0223", "Remoraid");
        SPECIES_MAP.put("0224", "Octillery");
        SPECIES_MAP.put("0225", "Delibird");
        SPECIES_MAP.put("0226", "Mantine");
        SPECIES_MAP.put("0227", "Skarmory");
        SPECIES_MAP.put("0228", "Houndour");
        SPECIES_MAP.put("0229", "Houndoom");
        SPECIES_MAP.put("0230", "Kingdra");
        SPECIES_MAP.put("0231", "Phanpy");
        SPECIES_MAP.put("0232", "Donphan");
        SPECIES_MAP.put("0233", "Porygon2");
        SPECIES_MAP.put("0234", "Stantler");
        SPECIES_MAP.put("0235", "Smeargle");
        SPECIES_MAP.put("0236", "Tyrogue");
        SPECIES_MAP.put("0237", "Hitmontop");
        SPECIES_MAP.put("0238", "Smoochum");
        SPECIES_MAP.put("0239", "Elekid");
        SPECIES_MAP.put("0240", "Magby");
        SPECIES_MAP.put("0241", "Miltank");
        SPECIES_MAP.put("0242", "Blissey");
        SPECIES_MAP.put("0243", "Raikou");
        SPECIES_MAP.put("0244", "Entei");
        SPECIES_MAP.put("0245", "Suicune");
        SPECIES_MAP.put("0246", "Larvitar");
        SPECIES_MAP.put("0247", "Pupitar");
        SPECIES_MAP.put("0248", "Tyranitar");
        SPECIES_MAP.put("0249", "Lugia");
        SPECIES_MAP.put("0250", "Ho-Oh");
        SPECIES_MAP.put("0251", "Celebi");
        SPECIES_MAP.put("0252", "Treecko");
        SPECIES_MAP.put("0253", "Grovyle");
        SPECIES_MAP.put("0254", "Sceptile");
        SPECIES_MAP.put("0255", "Torchic");
        SPECIES_MAP.put("0256", "Combusken");
        SPECIES_MAP.put("0257", "Blaziken");
        SPECIES_MAP.put("0258", "Mudkip");
        SPECIES_MAP.put("0259", "Marshtomp");
        SPECIES_MAP.put("0260", "Swampert");
        SPECIES_MAP.put("0261", "Poochyena");
        SPECIES_MAP.put("0262", "Mightyena");
        SPECIES_MAP.put("0263", "Zigzagoon");
        SPECIES_MAP.put("0264", "Linoone");
        SPECIES_MAP.put("0265", "Wurmple");
        SPECIES_MAP.put("0266", "Silcoon");
        SPECIES_MAP.put("0267", "Beautifly");
        SPECIES_MAP.put("0268", "Cascoon");
        SPECIES_MAP.put("0269", "Dustox");
        SPECIES_MAP.put("0270", "Lotad");
        SPECIES_MAP.put("0271", "Lombre");
        SPECIES_MAP.put("0272", "Ludicolo");
        SPECIES_MAP.put("0273", "Seedot");
        SPECIES_MAP.put("0274", "Nuzleaf");
        SPECIES_MAP.put("0275", "Shiftry");
        SPECIES_MAP.put("0276", "Taillow");
        SPECIES_MAP.put("0277", "Swellow");
        SPECIES_MAP.put("0278", "Wingull");
        SPECIES_MAP.put("0279", "Pelipper");
        SPECIES_MAP.put("0280", "Ralts");
        SPECIES_MAP.put("0281", "Kirlia");
        SPECIES_MAP.put("0282", "Gardevoir");
        SPECIES_MAP.put("0283", "Surskit");
        SPECIES_MAP.put("0284", "Masquerain");
        SPECIES_MAP.put("0285", "Shroomish");
        SPECIES_MAP.put("0286", "Breloom");
        SPECIES_MAP.put("0287", "Slakoth");
        SPECIES_MAP.put("0288", "Vigoroth");
        SPECIES_MAP.put("0289", "Slaking");
        SPECIES_MAP.put("0290", "Nincada");
        SPECIES_MAP.put("0291", "Ninjask");
        SPECIES_MAP.put("0292", "Shedinja");
        SPECIES_MAP.put("0293", "Whismur");
        SPECIES_MAP.put("0294", "Loudred");
        SPECIES_MAP.put("0295", "Exploud");
        SPECIES_MAP.put("0296", "Makuhita");
        SPECIES_MAP.put("0297", "Hariyama");
        SPECIES_MAP.put("0298", "Azurill");
        SPECIES_MAP.put("0299", "Nosepass");
        SPECIES_MAP.put("0300", "Skitty");
        SPECIES_MAP.put("0301", "Delcatty");
        SPECIES_MAP.put("0302", "Sableye");
        SPECIES_MAP.put("0303", "Mawile");
        SPECIES_MAP.put("0304", "Aron");
        SPECIES_MAP.put("0305", "Lairon");
        SPECIES_MAP.put("0306", "Aggron");
        SPECIES_MAP.put("0307", "Meditite");
        SPECIES_MAP.put("0308", "Medicham");
        SPECIES_MAP.put("0309", "Electrike");
        SPECIES_MAP.put("0310", "Manectric");
        SPECIES_MAP.put("0311", "Plusle");
        SPECIES_MAP.put("0312", "Minun");
        SPECIES_MAP.put("0313", "Volbeat");
        SPECIES_MAP.put("0314", "Illumise");
        SPECIES_MAP.put("0315", "Roselia");
        SPECIES_MAP.put("0316", "Gulpin");
        SPECIES_MAP.put("0317", "Swalot");
        SPECIES_MAP.put("0318", "Carvanha");
        SPECIES_MAP.put("0319", "Sharpedo");
        SPECIES_MAP.put("0320", "Wailmer");
        SPECIES_MAP.put("0321", "Wailord");
        SPECIES_MAP.put("0322", "Numel");
        SPECIES_MAP.put("0323", "Camerupt");
        SPECIES_MAP.put("0324", "Torkoal");
        SPECIES_MAP.put("0325", "Spoink");
        SPECIES_MAP.put("0326", "Grumpig");
        SPECIES_MAP.put("0327", "Spinda");
        SPECIES_MAP.put("0328", "Trapinch");
        SPECIES_MAP.put("0329", "Vibrava");
        SPECIES_MAP.put("0330", "Flygon");
        SPECIES_MAP.put("0331", "Cacnea");
        SPECIES_MAP.put("0332", "Cacturne");
        SPECIES_MAP.put("0333", "Swablu");
        SPECIES_MAP.put("0334", "Altaria");
        SPECIES_MAP.put("0335", "Zangoose");
        SPECIES_MAP.put("0336", "Seviper");
        SPECIES_MAP.put("0337", "Lunatone");
        SPECIES_MAP.put("0338", "Solrock");
        SPECIES_MAP.put("0339", "Barboach");
        SPECIES_MAP.put("0340", "Whiscash");
        SPECIES_MAP.put("0341", "Corphish");
        SPECIES_MAP.put("0342", "Crawdaunt");
        SPECIES_MAP.put("0343", "Baltoy");
        SPECIES_MAP.put("0344", "Claydol");
        SPECIES_MAP.put("0345", "Lileep");
        SPECIES_MAP.put("0346", "Cradily");
        SPECIES_MAP.put("0347", "Anorith");
        SPECIES_MAP.put("0348", "Armaldo");
        SPECIES_MAP.put("0349", "Feebas");
        SPECIES_MAP.put("0350", "Milotic");
        SPECIES_MAP.put("0351", "Castform");
        SPECIES_MAP.put("0352", "Kecleon");
        SPECIES_MAP.put("0353", "Shuppet");
        SPECIES_MAP.put("0354", "Banette");
        SPECIES_MAP.put("0355", "Duskull");
        SPECIES_MAP.put("0356", "Dusclops");
        SPECIES_MAP.put("0357", "Tropius");
        SPECIES_MAP.put("0358", "Chimecho");
        SPECIES_MAP.put("0359", "Absol");
        SPECIES_MAP.put("0360", "Wynaut");
        SPECIES_MAP.put("0361", "Snorunt");
        SPECIES_MAP.put("0362", "Glalie");
        SPECIES_MAP.put("0363", "Spheal");
        SPECIES_MAP.put("0364", "Sealeo");
        SPECIES_MAP.put("0365", "Walrein");
        SPECIES_MAP.put("0366", "Clamperl");
        SPECIES_MAP.put("0367", "Huntail");
        SPECIES_MAP.put("0368", "Gorebyss");
        SPECIES_MAP.put("0369", "Relicanth");
        SPECIES_MAP.put("0370", "Luvdisc");
        SPECIES_MAP.put("0371", "Bagon");
        SPECIES_MAP.put("0372", "Shelgon");
        SPECIES_MAP.put("0373", "Salamence");
        SPECIES_MAP.put("0374", "Beldum");
        SPECIES_MAP.put("0375", "Metang");
        SPECIES_MAP.put("0376", "Metagross");
        SPECIES_MAP.put("0377", "Regirock");
        SPECIES_MAP.put("0378", "Regice");
        SPECIES_MAP.put("0379", "Registeel");
        SPECIES_MAP.put("0380", "Latias");
        SPECIES_MAP.put("0381", "Latios");
        SPECIES_MAP.put("0382", "Kyogre");
        SPECIES_MAP.put("0383", "Groudon");
        SPECIES_MAP.put("0384", "Rayquaza");
        SPECIES_MAP.put("0385", "Jirachi");
        SPECIES_MAP.put("0386", "Deoxys");
        SPECIES_MAP.put("0387", "Turtwig");
        SPECIES_MAP.put("0388", "Grotle");
        SPECIES_MAP.put("0389", "Torterra");
        SPECIES_MAP.put("0390", "Chimchar");
        SPECIES_MAP.put("0391", "Monferno");
        SPECIES_MAP.put("0392", "Infernape");
        SPECIES_MAP.put("0393", "Piplup");
        SPECIES_MAP.put("0394", "Prinplup");
        SPECIES_MAP.put("0395", "Empoleon");
        SPECIES_MAP.put("0396", "Starly");
        SPECIES_MAP.put("0397", "Staravia");
        SPECIES_MAP.put("0398", "Staraptor");
        SPECIES_MAP.put("0399", "Bidoof");
        SPECIES_MAP.put("0400", "Bibarel");
        SPECIES_MAP.put("0401", "Kricketot");
        SPECIES_MAP.put("0402", "Kricketune");
        SPECIES_MAP.put("0403", "Shinx");
        SPECIES_MAP.put("0404", "Luxio");
        SPECIES_MAP.put("0405", "Luxray");
        SPECIES_MAP.put("0406", "Budew");
        SPECIES_MAP.put("0407", "Roserade");
        SPECIES_MAP.put("0408", "Cranidos");
        SPECIES_MAP.put("0409", "Rampardos");
        SPECIES_MAP.put("0410", "Shieldon");
        SPECIES_MAP.put("0411", "Bastiodon");
        SPECIES_MAP.put("0412", "Burmy");
        SPECIES_MAP.put("0413", "Wormadam");
        SPECIES_MAP.put("0414", "Mothim");
        SPECIES_MAP.put("0415", "Combee");
        SPECIES_MAP.put("0416", "Vespiquen");
        SPECIES_MAP.put("0417", "Pachirisu");
        SPECIES_MAP.put("0418", "Buizel");
        SPECIES_MAP.put("0419", "Floatzel");
        SPECIES_MAP.put("0420", "Cherubi");
        SPECIES_MAP.put("0421", "Cherrim");
        SPECIES_MAP.put("0422", "Shellos");
        SPECIES_MAP.put("0423", "Gastrodon");
        SPECIES_MAP.put("0424", "Ambipom");
        SPECIES_MAP.put("0425", "Drifloon");
        SPECIES_MAP.put("0426", "Drifblim");
        SPECIES_MAP.put("0427", "Buneary");
        SPECIES_MAP.put("0428", "Lopunny");
        SPECIES_MAP.put("0429", "Mismagius");
        SPECIES_MAP.put("0430", "Honchkrow");
        SPECIES_MAP.put("0431", "Glameow");
        SPECIES_MAP.put("0432", "Purugly");
        SPECIES_MAP.put("0433", "Chingling");
        SPECIES_MAP.put("0434", "Stunky");
        SPECIES_MAP.put("0435", "Skuntank");
        SPECIES_MAP.put("0436", "Bronzor");
        SPECIES_MAP.put("0437", "Bronzong");
        SPECIES_MAP.put("0438", "Bonsly");
        SPECIES_MAP.put("0439", "Mime Jr.");
        SPECIES_MAP.put("0440", "Happiny");
        SPECIES_MAP.put("0441", "Chatot");
        SPECIES_MAP.put("0442", "Spiritomb");
        SPECIES_MAP.put("0443", "Gible");
        SPECIES_MAP.put("0444", "Gabite");
        SPECIES_MAP.put("0445", "Garchomp");
        SPECIES_MAP.put("0446", "Munchlax");
        SPECIES_MAP.put("0447", "Riolu");
        SPECIES_MAP.put("0448", "Lucario");
        SPECIES_MAP.put("0449", "Hippopotas");
        SPECIES_MAP.put("0450", "Hippowdon");
        SPECIES_MAP.put("0451", "Skorupi");
        SPECIES_MAP.put("0452", "Drapion");
        SPECIES_MAP.put("0453", "Croagunk");
        SPECIES_MAP.put("0454", "Toxicroak");
        SPECIES_MAP.put("0455", "Carnivine");
        SPECIES_MAP.put("0456", "Finneon");
        SPECIES_MAP.put("0457", "Lumineon");
        SPECIES_MAP.put("0458", "Mantyke");
        SPECIES_MAP.put("0459", "Snover");
        SPECIES_MAP.put("0460", "Abomasnow");
        SPECIES_MAP.put("0461", "Weavile");
        SPECIES_MAP.put("0462", "Magnezone");
        SPECIES_MAP.put("0463", "Lickilicky");
        SPECIES_MAP.put("0464", "Rhyperior");
        SPECIES_MAP.put("0465", "Tangrowth");
        SPECIES_MAP.put("0466", "Electivire");
        SPECIES_MAP.put("0467", "Magmortar");
        SPECIES_MAP.put("0468", "Togekiss");
        SPECIES_MAP.put("0469", "Yanmega");
        SPECIES_MAP.put("0470", "Leafeon");
        SPECIES_MAP.put("0471", "Glaceon");
        SPECIES_MAP.put("0472", "Gliscor");
        SPECIES_MAP.put("0473", "Mamoswine");
        SPECIES_MAP.put("0474", "Porygon-Z");
        SPECIES_MAP.put("0475", "Gallade");
        SPECIES_MAP.put("0476", "Probopass");
        SPECIES_MAP.put("0477", "Dusknoir");
        SPECIES_MAP.put("0478", "Froslass");
        SPECIES_MAP.put("0479", "Rotom");
        SPECIES_MAP.put("0480", "Uxie");
        SPECIES_MAP.put("0481", "Mesprit");
        SPECIES_MAP.put("0482", "Azelf");
        SPECIES_MAP.put("0483", "Dialga");
        SPECIES_MAP.put("0484", "Palkia");
        SPECIES_MAP.put("0485", "Heatran");
        SPECIES_MAP.put("0486", "Regigigas");
        SPECIES_MAP.put("0487", "Giratina");
        SPECIES_MAP.put("0488", "Cresselia");
        SPECIES_MAP.put("0489", "Phione");
        SPECIES_MAP.put("0490", "Manaphy");
        SPECIES_MAP.put("0491", "Darkrai");
        SPECIES_MAP.put("0492", "Shaymin");
        SPECIES_MAP.put("0493", "Arceus");
        SPECIES_MAP.put("0494", "Victini");
        SPECIES_MAP.put("0495", "Snivy");
        SPECIES_MAP.put("0496", "Servine");
        SPECIES_MAP.put("0497", "Serperior");
        SPECIES_MAP.put("0498", "Tepig");
        SPECIES_MAP.put("0499", "Pignite");
        SPECIES_MAP.put("0500", "Emboar");
        SPECIES_MAP.put("0501", "Oshawott");
        SPECIES_MAP.put("0502", "Dewott");
        SPECIES_MAP.put("0503", "Samurott");
        SPECIES_MAP.put("0504", "Patrat");
        SPECIES_MAP.put("0505", "Watchog");
        SPECIES_MAP.put("0506", "Lillipup");
        SPECIES_MAP.put("0507", "Herdier");
        SPECIES_MAP.put("0508", "Stoutland");
        SPECIES_MAP.put("0509", "Purrloin");
        SPECIES_MAP.put("0510", "Liepard");
        SPECIES_MAP.put("0511", "Pansage");
        SPECIES_MAP.put("0512", "Simisage");
        SPECIES_MAP.put("0513", "Pansear");
        SPECIES_MAP.put("0514", "Simisear");
        SPECIES_MAP.put("0515", "Panpour");
        SPECIES_MAP.put("0516", "Simipour");
        SPECIES_MAP.put("0517", "Munna");
        SPECIES_MAP.put("0518", "Musharna");
        SPECIES_MAP.put("0519", "Pidove");
        SPECIES_MAP.put("0520", "Tranquill");
        SPECIES_MAP.put("0521", "Unfezant");
        SPECIES_MAP.put("0522", "Blitzle");
        SPECIES_MAP.put("0523", "Zebstrika");
        SPECIES_MAP.put("0524", "Roggenrola");
        SPECIES_MAP.put("0525", "Boldore");
        SPECIES_MAP.put("0526", "Gigalith");
        SPECIES_MAP.put("0527", "Woobat");
        SPECIES_MAP.put("0528", "Swoobat");
        SPECIES_MAP.put("0529", "Drilbur");
        SPECIES_MAP.put("0530", "Excadrill");
        SPECIES_MAP.put("0531", "Audino");
        SPECIES_MAP.put("0532", "Timburr");
        SPECIES_MAP.put("0533", "Gurdurr");
        SPECIES_MAP.put("0534", "Conkeldurr");
        SPECIES_MAP.put("0535", "Tympole");
        SPECIES_MAP.put("0536", "Palpitoad");
        SPECIES_MAP.put("0537", "Seismitoad");
        SPECIES_MAP.put("0538", "Throh");
        SPECIES_MAP.put("0539", "Sawk");
        SPECIES_MAP.put("0540", "Sewaddle");
        SPECIES_MAP.put("0541", "Swadloon");
        SPECIES_MAP.put("0542", "Leavanny");
        SPECIES_MAP.put("0543", "Venipede");
        SPECIES_MAP.put("0544", "Whirlipede");
        SPECIES_MAP.put("0545", "Scolipede");
        SPECIES_MAP.put("0546", "Cottonee");
        SPECIES_MAP.put("0547", "Whimsicott");
        SPECIES_MAP.put("0548", "Petilil");
        SPECIES_MAP.put("0549", "Lilligant");
        SPECIES_MAP.put("0550", "Basculin");
        SPECIES_MAP.put("0551", "Sandile");
        SPECIES_MAP.put("0552", "Krokorok");
        SPECIES_MAP.put("0553", "Krookodile");
        SPECIES_MAP.put("0554", "Darumaka");
        SPECIES_MAP.put("0555", "Darmanitan");
        SPECIES_MAP.put("0556", "Maractus");
        SPECIES_MAP.put("0557", "Dwebble");
        SPECIES_MAP.put("0558", "Crustle");
        SPECIES_MAP.put("0559", "Scraggy");
        SPECIES_MAP.put("0560", "Scrafty");
        SPECIES_MAP.put("0561", "Sigilyph");
        SPECIES_MAP.put("0562", "Yamask");
        SPECIES_MAP.put("0563", "Cofagrigus");
        SPECIES_MAP.put("0564", "Tirtouga");
        SPECIES_MAP.put("0565", "Carracosta");
        SPECIES_MAP.put("0566", "Archen");
        SPECIES_MAP.put("0567", "Archeops");
        SPECIES_MAP.put("0568", "Trubbish");
        SPECIES_MAP.put("0569", "Garbodor");
        SPECIES_MAP.put("0570", "Zorua");
        SPECIES_MAP.put("0571", "Zoroark");
        SPECIES_MAP.put("0572", "Minccino");
        SPECIES_MAP.put("0573", "Cinccino");
        SPECIES_MAP.put("0574", "Gothita");
        SPECIES_MAP.put("0575", "Gothorita");
        SPECIES_MAP.put("0576", "Gothitelle");
        SPECIES_MAP.put("0577", "Solosis");
        SPECIES_MAP.put("0578", "Duosion");
        SPECIES_MAP.put("0579", "Reuniclus");
        SPECIES_MAP.put("0580", "Ducklett");
        SPECIES_MAP.put("0581", "Swanna");
        SPECIES_MAP.put("0582", "Vanillite");
        SPECIES_MAP.put("0583", "Vanillish");
        SPECIES_MAP.put("0584", "Vanilluxe");
        SPECIES_MAP.put("0585", "Deerling");
        SPECIES_MAP.put("0586", "Sawsbuck");
        SPECIES_MAP.put("0587", "Emolga");
        SPECIES_MAP.put("0588", "Karrablast");
        SPECIES_MAP.put("0589", "Escavalier");
        SPECIES_MAP.put("0590", "Foongus");
        SPECIES_MAP.put("0591", "Amoonguss");
        SPECIES_MAP.put("0592", "Frillish");
        SPECIES_MAP.put("0593", "Jellicent");
        SPECIES_MAP.put("0594", "Alomomola");
        SPECIES_MAP.put("0595", "Joltik");
        SPECIES_MAP.put("0596", "Galvantula");
        SPECIES_MAP.put("0597", "Ferroseed");
        SPECIES_MAP.put("0598", "Ferrothorn");
        SPECIES_MAP.put("0599", "Klink");
        SPECIES_MAP.put("0600", "Klang");
        SPECIES_MAP.put("0601", "Klinklang");
        SPECIES_MAP.put("0602", "Tynamo");
        SPECIES_MAP.put("0603", "Eelektrik");
        SPECIES_MAP.put("0604", "Eelektross");
        SPECIES_MAP.put("0605", "Elgyem");
        SPECIES_MAP.put("0606", "Beheeyem");
        SPECIES_MAP.put("0607", "Litwick");
        SPECIES_MAP.put("0608", "Lampent");
        SPECIES_MAP.put("0609", "Chandelure");
        SPECIES_MAP.put("0610", "Axew");
        SPECIES_MAP.put("0611", "Fraxure");
        SPECIES_MAP.put("0612", "Haxorus");
        SPECIES_MAP.put("0613", "Cubchoo");
        SPECIES_MAP.put("0614", "Beartic");
        SPECIES_MAP.put("0615", "Cryogonal");
        SPECIES_MAP.put("0616", "Shelmet");
        SPECIES_MAP.put("0617", "Accelgor");
        SPECIES_MAP.put("0618", "Stunfisk");
        SPECIES_MAP.put("0619", "Mienfoo");
        SPECIES_MAP.put("0620", "Mienshao");
        SPECIES_MAP.put("0621", "Druddigon");
        SPECIES_MAP.put("0622", "Golett");
        SPECIES_MAP.put("0623", "Golurk");
        SPECIES_MAP.put("0624", "Pawniard");
        SPECIES_MAP.put("0625", "Bisharp");
        SPECIES_MAP.put("0626", "Bouffalant");
        SPECIES_MAP.put("0627", "Rufflet");
        SPECIES_MAP.put("0628", "Braviary");
        SPECIES_MAP.put("0629", "Vullaby");
        SPECIES_MAP.put("0630", "Mandibuzz");
        SPECIES_MAP.put("0631", "Heatmor");
        SPECIES_MAP.put("0632", "Durant");
        SPECIES_MAP.put("0633", "Deino");
        SPECIES_MAP.put("0634", "Zweilous");
        SPECIES_MAP.put("0635", "Hydreigon");
        SPECIES_MAP.put("0636", "Larvesta");
        SPECIES_MAP.put("0637", "Volcarona");
        SPECIES_MAP.put("0638", "Cobalion");
        SPECIES_MAP.put("0639", "Terrakion");
        SPECIES_MAP.put("0640", "Virizion");
        SPECIES_MAP.put("0641", "Tornadus");
        SPECIES_MAP.put("0642", "Thundurus");
        SPECIES_MAP.put("0643", "Reshiram");
        SPECIES_MAP.put("0644", "Zekrom");
        SPECIES_MAP.put("0645", "Landorus");
        SPECIES_MAP.put("0646", "Kyurem");
        SPECIES_MAP.put("0647", "Keldeo");
        SPECIES_MAP.put("0648", "Meloetta");
        SPECIES_MAP.put("0649", "Genesect");
        SPECIES_MAP.put("0701", "Furfrou");
        SPECIES_MAP.put("0702", "Phantump");
        SPECIES_MAP.put("0703", "Trevenant");
        SPECIES_MAP.put("0704", "Litleo");
        SPECIES_MAP.put("0705", "Pyroar");
        SPECIES_MAP.put("0706", "Scatterbug");
        SPECIES_MAP.put("0707", "Spewpa");
        SPECIES_MAP.put("0708", "Vivillon");
        SPECIES_MAP.put("0709", "Skrelp");
        SPECIES_MAP.put("0710", "Dragalge");
        SPECIES_MAP.put("0711", "Bunnelby");
        SPECIES_MAP.put("0712", "Diggersby");
        SPECIES_MAP.put("0713", "Flabébé");
        SPECIES_MAP.put("0714", "Floette");
        SPECIES_MAP.put("0715", "Florges");
        SPECIES_MAP.put("0716", "Noibat");
        SPECIES_MAP.put("0717", "Fennekin");
        SPECIES_MAP.put("0718", "Braixen");
        SPECIES_MAP.put("0719", "Delphox");
        SPECIES_MAP.put("0720", "Chespin");
        SPECIES_MAP.put("0721", "Quilladin");
        SPECIES_MAP.put("0722", "Chesnaught");
        SPECIES_MAP.put("0723", "Froakie");
        SPECIES_MAP.put("0724", "Frogadier");
        SPECIES_MAP.put("0725", "Greninja");
        SPECIES_MAP.put("0726", "Inkay");
        SPECIES_MAP.put("0727", "Malamar");
        SPECIES_MAP.put("0728", "Skiddo");
        SPECIES_MAP.put("0729", "Gogoat");
        SPECIES_MAP.put("0730", "Pangoro");
        SPECIES_MAP.put("0731", "Helioptile");
        SPECIES_MAP.put("0732", "Heliolisk");
        SPECIES_MAP.put("0733", "Espurr");
        SPECIES_MAP.put("0734", "Meowstic");
        SPECIES_MAP.put("0735", "Pumpkaboo");
        SPECIES_MAP.put("0736", "Gourgeist");
        SPECIES_MAP.put("0737", "Tyrunt");
        SPECIES_MAP.put("0738", "Tyrantrum");
        SPECIES_MAP.put("0739", "Amaura");
        SPECIES_MAP.put("0740", "Aurorus");
        SPECIES_MAP.put("0741", "Dedenne");
        SPECIES_MAP.put("0742", "Swirlix");
        SPECIES_MAP.put("0743", "Slurpuff");
        SPECIES_MAP.put("0744", "Honedge");
        SPECIES_MAP.put("0745", "Doublade");
        SPECIES_MAP.put("0746", "Aegislash");
        SPECIES_MAP.put("0747", "Binacle");
        SPECIES_MAP.put("0748", "Barbaracle");
        SPECIES_MAP.put("0749", "Bergmite");
        SPECIES_MAP.put("0751", "Avalugg");
        SPECIES_MAP.put("0752", "Pancham");
        SPECIES_MAP.put("0753", "Fletchling");
        SPECIES_MAP.put("0754", "Fletchinder");
        SPECIES_MAP.put("0755", "Talonflame");
        SPECIES_MAP.put("0756", "Clauncher");
        SPECIES_MAP.put("0757", "Clawitzer");
        SPECIES_MAP.put("0758", "Spritzee");
        SPECIES_MAP.put("0759", "Aromatisse");
        SPECIES_MAP.put("0760", "Klefki");
        SPECIES_MAP.put("0761", "Hawlucha");
        SPECIES_MAP.put("0762", "Noivern");
        SPECIES_MAP.put("0763", "Goomy");
        SPECIES_MAP.put("0764", "Sliggoo");
        SPECIES_MAP.put("0765", "Goodra");
        SPECIES_MAP.put("0766", "Carbink");
        SPECIES_MAP.put("0767", "Sylveon");
        SPECIES_MAP.put("0768", "Xerneas");
        SPECIES_MAP.put("0769", "Yveltal");
        SPECIES_MAP.put("0770", "Zygarde");
        SPECIES_MAP.put("0772", "Diancie");
        SPECIES_MAP.put("0773", "Volcanion");
        SPECIES_MAP.put("0774", "Hoopa");
        SPECIES_MAP.put("0801", "Mareanie");
        SPECIES_MAP.put("0802", "Toxapex");
        SPECIES_MAP.put("0803", "Morelull");
        SPECIES_MAP.put("0804", "Shiinotic");
        SPECIES_MAP.put("0805", "Salandit");
        SPECIES_MAP.put("0806", "Salazzle");
        SPECIES_MAP.put("0807", "Pikipek");
        SPECIES_MAP.put("0808", "Trumbeak");
        SPECIES_MAP.put("0809", "Toucannon");
        SPECIES_MAP.put("0810", "Oranguru");
        SPECIES_MAP.put("0811", "Komala");
        SPECIES_MAP.put("0812", "Bounsweet");
        SPECIES_MAP.put("0813", "Steenee");
        SPECIES_MAP.put("0814", "Tsareena");
        SPECIES_MAP.put("0815", "Passimian");
        SPECIES_MAP.put("0816", "Jangmo-o");
        SPECIES_MAP.put("0817", "Hakamo-o");
        SPECIES_MAP.put("0818", "Kommo-o");
        SPECIES_MAP.put("0819", "Mimikyu");
        SPECIES_MAP.put("0820", "Wishiwashi");
        SPECIES_MAP.put("0821", "Pyukumuku");
        SPECIES_MAP.put("0822", "Sandygast");
        SPECIES_MAP.put("0823", "Palossand");
        SPECIES_MAP.put("0824", "Minior");
        SPECIES_MAP.put("0825", "Oricorio");
        SPECIES_MAP.put("0826", "Yungoos");
        SPECIES_MAP.put("0827", "Gumshoos");
        SPECIES_MAP.put("0828", "Rockruff");
        SPECIES_MAP.put("0829", "Lycanroc");
        SPECIES_MAP.put("0830", "Tapu Koko");
        SPECIES_MAP.put("0831", "Tapu Lele");
        SPECIES_MAP.put("0832", "Tapu Bulu");
        SPECIES_MAP.put("0833", "Tapu Fini");
        SPECIES_MAP.put("0834", "Cutiefly");
        SPECIES_MAP.put("0835", "Ribombee");
        SPECIES_MAP.put("0836", "Grubbin");
        SPECIES_MAP.put("0837", "Charjabug");
        SPECIES_MAP.put("0838", "Vikavolt");
        SPECIES_MAP.put("0839", "Mudbray");
        SPECIES_MAP.put("0840", "Mudsdale");
        SPECIES_MAP.put("0841", "Rowlet");
        SPECIES_MAP.put("0842", "Dartrix");
        SPECIES_MAP.put("0843", "Decidueye");
        SPECIES_MAP.put("0844", "Litten");
        SPECIES_MAP.put("0845", "Torracat");
        SPECIES_MAP.put("0846", "Incineroar");
        SPECIES_MAP.put("0847", "Popplio");
        SPECIES_MAP.put("0848", "Brionne");
        SPECIES_MAP.put("0849", "Primarina");
        SPECIES_MAP.put("0850", "Dewpider");
        SPECIES_MAP.put("0851", "Araquanid");
        SPECIES_MAP.put("0852", "Stufful");
        SPECIES_MAP.put("0853", "Bewear");
        SPECIES_MAP.put("0854", "Turtonator");
        SPECIES_MAP.put("0855", "Bruxish");
        SPECIES_MAP.put("0856", "Drampa");
        SPECIES_MAP.put("0857", "Dhelmise");
        SPECIES_MAP.put("0858", "Togedemaru");
        SPECIES_MAP.put("0859", "Crabrawler");
        SPECIES_MAP.put("0860", "Crabominable");
        SPECIES_MAP.put("0861", "Type: Null");
        SPECIES_MAP.put("0862", "Silvally");
        SPECIES_MAP.put("0863", "Comfey");
        SPECIES_MAP.put("0865", "Necrozma");
        SPECIES_MAP.put("0866", "Wimpod");
        SPECIES_MAP.put("0867", "Golisopod");
        SPECIES_MAP.put("0868", "Fomantis");
        SPECIES_MAP.put("0869", "Lurantis");
        SPECIES_MAP.put("0871", "Cosmog");
        SPECIES_MAP.put("0872", "Cosmoem");
        SPECIES_MAP.put("0873", "Solgaleo");
        SPECIES_MAP.put("0874", "Lunala");
        SPECIES_MAP.put("0875", "Nihilego");
        SPECIES_MAP.put("0876", "Guzzlord");
        SPECIES_MAP.put("0877", "Buzzwole");
        SPECIES_MAP.put("0878", "Xurkitree");
        SPECIES_MAP.put("0879", "Pheromosa");
        SPECIES_MAP.put("0880", "Kartana");
        SPECIES_MAP.put("0881", "Celesteela");
        SPECIES_MAP.put("0882", "Magearna");
        SPECIES_MAP.put("0883", "Marshadow");
        SPECIES_MAP.put("0884", "Stakataka");
        SPECIES_MAP.put("0885", "Blacephalon");
        SPECIES_MAP.put("0886", "Poipole");
        SPECIES_MAP.put("0887", "Nagandel");
        SPECIES_MAP.put("0888", "Zeraora");
        SPECIES_MAP.put("0891", "Meltan");
        SPECIES_MAP.put("0892", "Melmetal");
        SPECIES_MAP.put("0901", "Nicket");
        SPECIES_MAP.put("0902", "Thievul");
        SPECIES_MAP.put("0903", "Chewtie");
        SPECIES_MAP.put("0904", "Drednaw");
        SPECIES_MAP.put("0905", "Gossifleur");
        SPECIES_MAP.put("0906", "Eldegoss");
        SPECIES_MAP.put("0907", "Yamper");
        SPECIES_MAP.put("0908", "Boltund");
        SPECIES_MAP.put("0909", "Skwovet");
        SPECIES_MAP.put("0910", "Greedent");
        SPECIES_MAP.put("0911", "Wooloo");
        SPECIES_MAP.put("0912", "Dubwool");
        SPECIES_MAP.put("0913", "Arrokuda");
        SPECIES_MAP.put("0914", "Barraskewda");
        SPECIES_MAP.put("0915", "Sizzlipede");
        SPECIES_MAP.put("0916", "Centiskorch");
        SPECIES_MAP.put("0917", "Cramorant");
        SPECIES_MAP.put("0918", "Rookidee");
        SPECIES_MAP.put("0919", "Corvisquire");
        SPECIES_MAP.put("0920", "Corviknight");
        SPECIES_MAP.put("0921", "Toxel");
        SPECIES_MAP.put("0922", "Toxitricity");
        SPECIES_MAP.put("0923", "Falinks");
        SPECIES_MAP.put("0924", "Milcery");
        SPECIES_MAP.put("0925", "Alcremie");
        SPECIES_MAP.put("0926", "Cufant");
        SPECIES_MAP.put("0927", "Copperajah");
        SPECIES_MAP.put("0928", "Obstagoon");
        SPECIES_MAP.put("0929", "Duraludon");
        SPECIES_MAP.put("0930", "Blipbug");
        SPECIES_MAP.put("0931", "Dottler");
        SPECIES_MAP.put("0932", "Orbeetle");
        SPECIES_MAP.put("0933", "Rolycoly");
        SPECIES_MAP.put("0934", "Carkoal");
        SPECIES_MAP.put("0935", "Coalossal");
        SPECIES_MAP.put("0936", "Silicobra");
        SPECIES_MAP.put("0937", "Sandaconda");
        SPECIES_MAP.put("0938", "Zacian");
        SPECIES_MAP.put("0939", "Zamazenta");
        SPECIES_MAP.put("0940", "Eternatus");
        SPECIES_MAP.put("0941", "Morpeko");
        SPECIES_MAP.put("0942", "Indeedee");
        SPECIES_MAP.put("0943", "Perrserker");
        SPECIES_MAP.put("0944", "Pincurchin");
        SPECIES_MAP.put("0945", "Snom");
        SPECIES_MAP.put("0946", "Frosmoth");
        SPECIES_MAP.put("0947", "Cursola");
        SPECIES_MAP.put("0948", "Grookey");
        SPECIES_MAP.put("0949", "Thwackey");
        SPECIES_MAP.put("0950", "Rillaboom");
        SPECIES_MAP.put("0951", "Sobble");
        SPECIES_MAP.put("0952", "Drizzile");
        SPECIES_MAP.put("0953", "Inteleon");
        SPECIES_MAP.put("0954", "Scorbunny");
        SPECIES_MAP.put("0955", "Raboot");
        SPECIES_MAP.put("0956", "Cinderace");
        SPECIES_MAP.put("0957", "Impidimp");
        SPECIES_MAP.put("0958", "Morgrem");
        SPECIES_MAP.put("0959", "Grimmsnarl");
        SPECIES_MAP.put("0960", "Dracozolt");
        SPECIES_MAP.put("0961", "Arctozolt");
        SPECIES_MAP.put("0962", "Dracovish");
        SPECIES_MAP.put("0963", "Arctovish");
        SPECIES_MAP.put("0964", "Clobbopus");
        SPECIES_MAP.put("0965", "Grapploct");
        SPECIES_MAP.put("0966", "Applin");
        SPECIES_MAP.put("0967", "Flapple");
        SPECIES_MAP.put("0968", "Appletun");
        SPECIES_MAP.put("0969", "Hattena");
        SPECIES_MAP.put("0970", "Hattrem");
        SPECIES_MAP.put("0971", "Hatterene");
        SPECIES_MAP.put("0972", "Sinistea");
        SPECIES_MAP.put("0973", "Polteageist");
        SPECIES_MAP.put("0974", "Stonjourner");
        SPECIES_MAP.put("0975", "Eiscue");
        SPECIES_MAP.put("0976", "Dreepy");
        SPECIES_MAP.put("0977", "Drakloak");
        SPECIES_MAP.put("0978", "Dragapult");
        SPECIES_MAP.put("0979", "Runerigus");
        SPECIES_MAP.put("0980", "Mr. Rime");
        SPECIES_MAP.put("0981", "Sirfetch'd");
        SPECIES_MAP.put("0982", "Kubfu");
        SPECIES_MAP.put("0983", "Urshifu");
        SPECIES_MAP.put("0984", "Glastrier");
        SPECIES_MAP.put("0985", "Spectrier");
        SPECIES_MAP.put("0986", "Calyrex");
        SPECIES_MAP.put("0988", "Zarude");
        SPECIES_MAP.put("0989", "Regieleki");
        SPECIES_MAP.put("0990", "Regidrago");
        SPECIES_MAP.put("1001", "Wyrdeer");
        SPECIES_MAP.put("1002", "Kleavor");
        SPECIES_MAP.put("1003", "Sneasler");
        SPECIES_MAP.put("1004", "Enamorus");
        SPECIES_MAP.put("1005", "Overqwil");
        SPECIES_MAP.put("1006", "Basculegion");
        SPECIES_MAP.put("1007", "Ursaluna");
        SPECIES_MAP.put("1010", "Sprigatito");
        SPECIES_MAP.put("1011", "Floragato");
        SPECIES_MAP.put("1012", "Meowscarada");
        SPECIES_MAP.put("1013", "Fuecoco");
        SPECIES_MAP.put("1014", "Crocalor");
        SPECIES_MAP.put("1015", "Skeledirge");
        SPECIES_MAP.put("1016", "Quaxly");
        SPECIES_MAP.put("1017", "Quaxwell");
        SPECIES_MAP.put("1018", "Quaquaval");
        SPECIES_MAP.put("1019", "Lechonk");
        SPECIES_MAP.put("1020", "Oinkologne");
        SPECIES_MAP.put("1021", "Dudunsparce");
        SPECIES_MAP.put("1022", "Tarountula");
        SPECIES_MAP.put("1023", "Spidops");
        SPECIES_MAP.put("1024", "Nymble");
        SPECIES_MAP.put("1025", "Lokix");
        SPECIES_MAP.put("1026", "Rellor");
        SPECIES_MAP.put("1027", "Rabsca");
        SPECIES_MAP.put("1028", "Greavard");
        SPECIES_MAP.put("1029", "Houndstone");
        SPECIES_MAP.put("1030", "Flittle");
        SPECIES_MAP.put("1031", "Espathra");
        SPECIES_MAP.put("1032", "Firagarif");
        SPECIES_MAP.put("1033", "Wiglett");
        SPECIES_MAP.put("1034", "Wugtrio");
        SPECIES_MAP.put("1035", "Dondozo");
        SPECIES_MAP.put("1036", "Veluza");
        SPECIES_MAP.put("1037", "Finizen");
        SPECIES_MAP.put("1038", "Palafin");
        SPECIES_MAP.put("1039", "Smoliv");
        SPECIES_MAP.put("1040", "Dolliv");
        SPECIES_MAP.put("1041", "Arboliva");
        SPECIES_MAP.put("1042", "Capsakid");
        SPECIES_MAP.put("1043", "Scovillain");
        SPECIES_MAP.put("1044", "Tadbulb");
        SPECIES_MAP.put("1045", "Bellibolt");
        SPECIES_MAP.put("1046", "Varoom");
        SPECIES_MAP.put("1047", "Revavroom");
        SPECIES_MAP.put("1048", "Orthworm");
        SPECIES_MAP.put("1049", "Tandemaus");
        SPECIES_MAP.put("1050", "Maushold");
        SPECIES_MAP.put("1051", "Cetoddle");
        SPECIES_MAP.put("1052", "Cetitan");
        SPECIES_MAP.put("1053", "Arbolovia");
        SPECIES_MAP.put("1054", "Arctibax");
        SPECIES_MAP.put("1055", "Baxcalibur");
        SPECIES_MAP.put("1056", "Tatsugiri");
        SPECIES_MAP.put("1057", "Cyclizar");
        SPECIES_MAP.put("1058", "Pawmi");
        SPECIES_MAP.put("1059", "Pawmo");
        SPECIES_MAP.put("1060", "Pawmot");
        SPECIES_MAP.put("1061", "Wattrel");
        SPECIES_MAP.put("1062", "Kilowattrel");
        SPECIES_MAP.put("1063", "Bombirdier");
        SPECIES_MAP.put("1064", "Squawkabilly");
        SPECIES_MAP.put("1065", "Flamigo");
        SPECIES_MAP.put("1066", "Klawf");
        SPECIES_MAP.put("1067", "Nacl");
        SPECIES_MAP.put("1068", "Naclstack");
        SPECIES_MAP.put("1069", "Garganacl");
        SPECIES_MAP.put("1070", "Glimmet");
        SPECIES_MAP.put("1071", "Glimmora");
        SPECIES_MAP.put("1072", "Shroodle");
        SPECIES_MAP.put("1073", "Grafaiai");
        SPECIES_MAP.put("1074", "Fidough");
        SPECIES_MAP.put("1075", "Dachsbun");
        SPECIES_MAP.put("1076", "Maschiff");
        SPECIES_MAP.put("1077", "Mabosstiff");
        SPECIES_MAP.put("1078", "Bramblin");
        SPECIES_MAP.put("1079", "Brambleghast");
        SPECIES_MAP.put("1080", "Gimmighoul");
        SPECIES_MAP.put("1081", "Gholdengo");
        SPECIES_MAP.put("1082", "Great Tusk");
        SPECIES_MAP.put("1083", "Brute Bonnet");
        SPECIES_MAP.put("1084", "Walking Wake");
        SPECIES_MAP.put("1085", "Sandy Shocks");
        SPECIES_MAP.put("1086", "Scream Tail");
        SPECIES_MAP.put("1087", "Flutter Mane");
        SPECIES_MAP.put("1088", "Slither Wing");
        SPECIES_MAP.put("1089", "Roaring Moon");
        SPECIES_MAP.put("1090", "Iron Treads");
        SPECIES_MAP.put("1091", "Iron Leaves");
        SPECIES_MAP.put("1092", "Iron Moth");
        SPECIES_MAP.put("1093", "Iron Hands");
        SPECIES_MAP.put("1094", "Iron Jugulis");
        SPECIES_MAP.put("1095", "Iron Thorns");
        SPECIES_MAP.put("1096", "Iron Bundle");
        SPECIES_MAP.put("1097", "Iron Valiant");
        SPECIES_MAP.put("1098", "Ting-Lu");
        SPECIES_MAP.put("1099", "Chien-Pao");
        SPECIES_MAP.put("1100", "Wo-Chien");
        SPECIES_MAP.put("1101", "Chi-Yu");
        SPECIES_MAP.put("1102", "Koraidon");
        SPECIES_MAP.put("1103", "Miraidon");
        SPECIES_MAP.put("1104", "Tinkatink");
        SPECIES_MAP.put("1105", "Tinkatuff");
        SPECIES_MAP.put("1106", "Tinkaton");
        SPECIES_MAP.put("1107", "Charcadet");
        SPECIES_MAP.put("1108", "Armarouge");
        SPECIES_MAP.put("1109", "Ceruledge");
        SPECIES_MAP.put("1110", "Toedscool");
        SPECIES_MAP.put("1111", "Toedscruel");
        SPECIES_MAP.put("1112", "Kingambit");
        SPECIES_MAP.put("1113", "Clodsire");
        SPECIES_MAP.put("1114", "Annihilape");
    }
}
